#server:
#  port: 8080
spring:
#  application:
#    name: pets-ms
#  jackson:
#    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
#      schema: pet
      minimum-idle: 10
      maximum-pool-size: 10
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  #    datasource:
  #      url: jdbc:h2:mem:test;MODE=PostgreSQL
  #      username: sa
  #      password: sa
  #      driver-class-name: org.h2.Driver
  #      hikari:
  #        minimum-idle: 10
  #        maximum-pool-size: 10
  #    jpa:
  #      hibernate.ddl-auto: none
  #      properties:
  #        hibernate:
  #          format_sql: true
  #          hibernate.dialect: org.hibernate.dialect.H2Dialect
  #          ddl-auto: update # Allow inserts when create H2 database
#  flyway:
#    validateOnMigrate: false
#    schemas: pet
#  redis:
#    sentinel:
#      master: mymaster
#      nodes: slnemesis01.sanitas.dom:26379,slnemesis02.sanitas.dom:26379
#    database: 11
#
#redis:
#  ttl:
#    pets: 3600 # In miliseconds
