spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Allow inserts when create database
  h2:
    console:
      enabled: true
      path: /h2-console
