-- DROP TABLES
DROP TABLE IF EXISTS pets CASCADE;

-- DROP SEQUENCES
DROP SEQUENCE IF EXISTS SQ_PETS;

-- CREATE SEQUENCES
CREATE SEQUENCE IF NOT EXISTS SQ_PETS;

-- CREATE TABLES
CREATE TABLE pets (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
